services:
  - type: web
    name: stayready
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars: []
    runtime: python3.11
